import 'package:hive_flutter/hive_flutter.dart';
import '../models/result_model.dart';

class HiveService {
  static const String _resultsBoxName = 'exam_results';
  static Box<ResultModel>? _resultsBox;

  /// Initialize Hive and register adapters
  static Future<void> init() async {
    await Hive.initFlutter();

    // Register adapters (generated by build_runner)
    if (!Hive.isAdapterRegistered(1)) {
      Hive.registerAdapter(ResultModelAdapter());
    }

    // Open boxes
    _resultsBox = await Hive.openBox<ResultModel>(_resultsBoxName);
  }

  /// Add a new result to Hive
  static Future<void> addResult(ResultModel result) async {
    await _resultsBox?.add(result);
  }

  /// Get all results sorted by date (latest first)
  static List<ResultModel> getAllResults() {
    final results = _resultsBox?.values.toList() ?? [];
    results.sort((a, b) => b.dateTime.compareTo(a.dateTime));
    return results;
  }

  /// Clear all results from history
  static Future<void> clearHistory() async {
    await _resultsBox?.clear();
  }

  /// Get results count
  static int getResultsCount() {
    return _resultsBox?.length ?? 0;
  }

  /// Get average score across all exams
  static double getAverageScore() {
    final results = getAllResults();
    if (results.isEmpty) return 0.0;

    final totalPercentage = results.fold<double>(
      0.0,
      (sum, result) => sum + result.percentage,
    );

    return totalPercentage / results.length;
  }

  /// Get results by category
  static List<ResultModel> getResultsByCategory(String category) {
    return getAllResults()
        .where((result) => result.category == category)
        .toList();
  }

  /// Close Hive boxes
  static Future<void> close() async {
    await _resultsBox?.close();
  }
}
